export const lipsum = `National Aeronautics and Space Administration (NASA)
MISSION: Since its establishment, NASA has helped to spur profound changes in our knowledge, culture, and expectations. Congress enacted the National Aeronautics and Space Act of 1958 “to provide for research into problems of flight within and outside Earth’s atmosphere” and to ensure that the United States conducts activities in space devoted to peaceful purposes for the benefit of humanity. We have since been instrumental in numerous scientific discoveries and technological advances that have advanced humankind, while inspiring the Nation and the world to imagine that much more is possible. We embrace the spirit, principles, and objectives of the original act and recent key policies and legislation in our Vision and Mission. NASA’s Vision: We reach for new heights and reveal the unknown for the benefit of humankind. NASA’s Mission: Drive advances in science, technology, aeronautics, and space exploration to enhance knowledge, education, innovation, economic vitality, and stewardship of Earth.  The following overarching approach governs the management and conduct of our aeronautics and space programs. These are standard practices that each organization within NASA employs in developing and executing their plans to achieve our strategic goals. They also provide a framework that guides our support for other areas of national and Administration policy: government transparency; science technology, engineering, and mathematics education; energy and climate change; innovation; and increased citizen and partnership participation to help address the multitude of challenges faced by our Nation.
Invest in next-generation technologies and approaches to spur innovation;
Inspire students to be our future scientists, engineers, explorers, and educators through interactions with NASA’s people, missions, research, and facilities;
Expand partnerships with international, intergovernmental, academic, industrial, and entrepreneurial communities, recognizing them as important contributors of skill and creativity to our missions and for the propagation of our results;
Commit to environmental stewardship through Earth observation and science, and the development and use of green technologies and capabilities in NASA missions and facilities; and
Safeguard the public trust through transparency and accountability in our programmatic and financial management, procurement, and reporting practices.
Since 1958, NASA has pioneered the future in human and robotic space exploration, scientific discovery, and aeronautics research. NASA is comprised of Headquarters in Washington, DC, nine Centers located around the country, and the Jet Propulsion Laboratory, a Federally Funded Research and Development Center operated under a contract with the California Institute of Technology. In addition, we have partnerships with academia, the private sector, state and local governments, other Federal agencies, and a number of international organizations, creating an extended NASA family of civil servants, contractors, allied partners, and stakeholders.
NASA’s work is implemented primarily by five Directorates and three offices:
Aeronautics Research conducts fundamental research in aeronautical disciplines and develops capabilities, tools, and technologies that will enhance aircraft performance, safety, and environmental compatibility, as well as increase the capacity and flexibility of the U.S. air transportation system.
Human Exploration and Operations provides the Agency with leadership and management of NASA space operations related to human exploration in and beyond low Earth orbit.
Science conducts the scientific exploration of Earth, the Sun, the solar system, and the universe through a wide variety of ground-, air-, and space-based missions and support systems.
Space Technology develops the cross-cutting, advanced and pioneering new technologies needed for NASA's current and future missions, many of which also benefit America's aerospace industries, other government agencies, and address national needs.
Mission Support coordinates the efficient and effective day-to-day operations and infrastructure critical to the Agency.
Office of Education helps to strengthen NASA and the Nation's future workforce, attract and retain students in science, technology, engineering and mathematics, or STEM, disciplines, and engage Americans in NASA's mission.
Office of the Chief Technologist provides policy, strategy and leadership that guides NASA’s technology and innovation activities, fosters technology transfer and commercialization for the benefit of the Nation, coordinates partnerships, prizes and challenges, and documents, tracks, and analyzes NASA’s technology investments ensuring they are consistent with NASA's technology needs and strategy.
Office of the Chief Scientist is the principal adviser to the NASA Administrator on NASA science programs, strategic planning and the evaluation of related investments. National Aeronautics and Space Administration (NASA)
MISSION: Since its establishment, NASA has helped to spur profound changes in our knowledge, culture, and expectations. Congress enacted the National Aeronautics and Space Act of 1958 “to provide for research into problems of flight within and outside Earth’s atmosphere” and to ensure that the United States conducts activities in space devoted to peaceful purposes for the benefit of humanity. We have since been instrumental in numerous scientific discoveries and technological advances that have advanced humankind, while inspiring the Nation and the world to imagine that much more is possible. We embrace the spirit, principles, and objectives of the original act and recent key policies and legislation in our Vision and Mission. NASA’s Vision: We reach for new heights and reveal the unknown for the benefit of humankind. NASA’s Mission: Drive advances in science, technology, aeronautics, and space exploration to enhance knowledge, education, innovation, economic vitality, and stewardship of Earth.  The following overarching approach governs the management and conduct of our aeronautics and space programs. These are standard practices that each organization within NASA employs in developing and executing their plans to achieve our strategic goals. They also provide a framework that guides our support for other areas of national and Administration policy: government transparency; science technology, engineering, and mathematics education; energy and climate change; innovation; and increased citizen and partnership participation to help address the multitude of challenges faced by our Nation.
Invest in next-generation technologies and approaches to spur innovation;
Inspire students to be our future scientists, engineers, explorers, and educators through interactions with NASA’s people, missions, research, and facilities;
Expand partnerships with international, intergovernmental, academic, industrial, and entrepreneurial communities, recognizing them as important contributors of skill and creativity to our missions and for the propagation of our results;
Commit to environmental stewardship through Earth observation and science, and the development and use of green technologies and capabilities in NASA missions and facilities; and
Safeguard the public trust through transparency and accountability in our programmatic and financial management, procurement, and reporting practices.
Since 1958, NASA has pioneered the future in human and robotic space exploration, scientific discovery, and aeronautics research. NASA is comprised of Headquarters in Washington, DC, nine Centers located around the country, and the Jet Propulsion Laboratory, a Federally Funded Research and Development Center operated under a contract with the California Institute of Technology. In addition, we have partnerships with academia, the private sector, state and local governments, other Federal agencies, and a number of international organizations, creating an extended NASA family of civil servants, contractors, allied partners, and stakeholders.
NASA’s work is implemented primarily by five Directorates and three offices:
Aeronautics Research conducts fundamental research in aeronautical disciplines and develops capabilities, tools, and technologies that will enhance aircraft performance, safety, and environmental compatibility, as well as increase the capacity and flexibility of the U.S. air transportation system.
Human Exploration and Operations provides the Agency with leadership and management of NASA space operations related to human exploration in and beyond low Earth orbit.
Science conducts the scientific exploration of Earth, the Sun, the solar system, and the universe through a wide variety of ground-, air-, and space-based missions and support systems.
Space Technology develops the cross-cutting, advanced and pioneering new technologies needed for NASA's current and future missions, many of which also benefit America's aerospace industries, other government agencies, and address national needs.
Mission Support coordinates the efficient and effective day-to-day operations and infrastructure critical to the Agency.
Office of Education helps to strengthen NASA and the Nation's future workforce, attract and retain students in science, technology, engineering and mathematics, or STEM, disciplines, and engage Americans in NASA's mission.
Office of the Chief Technologist provides policy, strategy and leadership that guides NASA’s technology and innovation activities, fosters technology transfer and commercialization for the benefit of the Nation, coordinates partnerships, prizes and challenges, and documents, tracks, and analyzes NASA’s technology investments ensuring they are consistent with NASA's technology needs and strategy.
Office of the Chief Scientist is the principal adviser to the NASA Administrator on NASA science programs, strategic planning and the evaluation of related investments.`;
