# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nate.jp
email: iamnbutler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  With over 6 years of experience in graphic design, front-end development and product design, Nate is a designer equipped to solve problems and drive innovation. His passion for technology and change are what drive the passion and focus behind his work. Fusing a love of functional design, future technology, culture, the sharing of knowledge and eternal drive for self improvement Nate’s work strives to connect people, improve lives and create lovable experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nate.jp" # the base hostname & protocol for your site
twitter_username: iamnbutler
github_username:  iamnbutler

# Gems
# gems:

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Collections
collections:
  journal:
    output: true
    permalink: /journal/:path/

# Assets
sass:
  sass_dir:          _scss
  style:            :compressed

assets:
  compress:
    css: true,
    js: false,

  autowrite: true
  cache: false
  cache_type: memory
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

  assets:
    - "*.png"
    - "*.jpg"
    - "bundle.css"

  sources:
    - _assets/scss
    - _assets/fonts
    - _assets/img
    - _assets/js
    - js
    - img