import '@/app/styles/global.css'
import '@/app/styles/tailwind.css';
import { Lora } from 'next/font/google'
const lora = Lora({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={lora.className}>
                <div className='site-background fixed z-0 top-0 bottom-0 left-0 right-0' />
                <div className='relative z-10'>{children}</div>
            </body>
        </html>
    )
}
