import '@/app/globals.css'
import '@/app/styles/tailwind.css';
import { Lora } from 'next/font/google'
const lora = Lora({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={lora.className}>{children}</body>
        </html>
    )
}
