backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # All posts
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    label_singular: "Post"
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}-{{year}}-{{month}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Show Post",
          name: "post_visible",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          # This isn't hooked up to anything yet
          label: "Custom Slug",
          name: "custom_slug",
          widget: "string",
          required: false,
        }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Summary", name: "summary", widget: "text" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Nate Butler",
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Last Updated",
          name: "date_updated",
          widget: "datetime",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - {
          label: "Show Thumbnail",
          name: "show_thumbnail",
          widget: "boolean",
          default: true,
          required: false,
        }
      - {
          label: "Thumbnail",
          name: "thumbnail",
          widget: "image",
          media_library: { config: { multiple: false } },
          media_folder: "/static/img/post/thumbnail",
          required: false,
        }
      - {
          label: "Wide Thumbnail",
          name: "prefer_wide_thumbnail",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Wide Thumbnail",
          name: "wide_thumbnail",
          widget: "image",
          media_library: { config: { multiple: false } },
          media_folder: "/static/img/post/thumbnail",
          required: false,
        }
      - {
          label: "Hero Image",
          name: "hero_image",
          widget: "image",
          media_library: { config: { multiple: false } },
          media_folder: "/static/img/post/hero",
          required: false,
        }
      - {
          label: "Image Gallery",
          name: "gallery_images",
          widget: "image",
          media_library: { config: { multiple: true } },
          media_folder: "/static/img/post/gallery",
          required: false,
        }
      - { label: "Edits", name: "edit", widget: "markdown", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Related Posts",
          name: "related_posts",
          widget: "list",
          required: false,
        }

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }

  # Work
  - name: "work"
    label: "Work"
    folder: "work"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["work"] }

  # social
  - name: "social"
    label: "Connect"
    folder: "social"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["social"] }

  # media
  - name: "media"
    label: "Mentions"
    folder: "media"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Outlet", name: "outlet", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Tags", name: "tags", widget: "list", default: ["media"] }
